# Code Test

In [2]:
import numpy as np
import scipy as sp
import jax
import jax.numpy as jnp

In [6]:
T = 3
N = 5
n = 6
m = 2
index = 0

s_mpc = np.zeros((T, N + 1, n))
u_mpc = np.zeros((T, N, m))

for t in range(T):
    for n in range(N):
        for mi in range(m):
            u_mpc[t, n, mi] = index
            index += 1


print(u_mpc)

u_init = np.concatenate([u_mpc[2, 1:], u_mpc[2, -1:]])

print(u_init)

[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]
  [ 8.  9.]]

 [[10. 11.]
  [12. 13.]
  [14. 15.]
  [16. 17.]
  [18. 19.]]

 [[20. 21.]
  [22. 23.]
  [24. 25.]
  [26. 27.]
  [28. 29.]]]
[[22. 23.]
 [24. 25.]
 [26. 27.]
 [28. 29.]
 [28. 29.]]


In [17]:
np.random.normal(1, 0.1)

0.8724046117787913

In [27]:
jax.random.normal(jax.random.PRNGKey(0))

Array(-0.20584226, dtype=float32)